### ISSUE TITLE
Exception decrypting ApplePay token

### ISSUE THREAD

**Issue by mavencode01** [beatty/applepay_crypto_demo#1]
I got this exception whenever I tried to decrypt the payment token

```
paymentTokenFilename = "payment_token.json";
merchantPkcFilename = "merchant.cer";
pkcs12Filename = "Certificates.p12";    //set .p12 password to "test"


return cipher.doFinal(ciphertext); throws this exception

Exception in thread "main" javax.crypto.BadPaddingException: mac check in GCM failed
at org.bouncycastle.jce.provider.JCEBlockCipher.engineDoFinal(Unknown Source)
at javax.crypto.Cipher.doFinal(DashoA13*..)
at com.wp.applepay.Main.decrypt(Main.java:133)
at com.wp.applepay.Main.main(Main.java:105)
```

Any help as to what am doing wrong ?

Thank you

**Comment by yavosh** [comment]
I got the same error when using the wrong merchant keys. Double check the merchant id used and make sure you are using the correct pub/priv key

**Comment by mavencode01** [comment]
I started all over again but still got the same error message:
Downloaded my merchant certificate using my Csr
Added it to my keychain and export the private key as .p12 ( save to disk, specify 256B/ECC)
I specified merchant certificate as my public key.
Got my paymenttoken from PKPayment object

I don't know what else am missing.

Any idea of what I did wrong ?

Thanks,

**Comment by feldmisco** [comment]
I'm having the same issue with the "mac check in GCM failed" and have also redone the cert, exported the key, etc.  I'm using the Apple Pay cert downloaded from the iOS Dev Center and exported the private key for that cert from the keychain.  

Has anyone run into this exception and figured out what the problem was?

Thank you!

**Comment by mavencode01** [comment]
Interestingly, I restarted everything again this morning, follow the same steps and it worked.
Am going to try to create another project & certificates to see if I can reproduce the issue again.

Right now, it's working for me :8ball:

**Comment by feldmisco** [comment]
Thank you for the quick reply.  That's quite interesting.  I'll do a new round of requests and certs and see if the decryption gods will smile up me.  :)  🎲🎲

**Comment by feldmisco** [comment]
I created a new merchant ID and certificate chain, and then everything worked!  Thank you!

**Comment by mavencode01** [comment]
The decryption gods smile on you :+1:
